# Generated by Django 6.0.7 on 2026-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_case_is_escalated_feedback_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='is_zero_fir',
            field=models.BooleanField(default=False),
        ),
    ]
